name: Workflow Reusable

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: true
      entorno:
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Mostrar valores
        run: |
          echo "Node version: ${{ inputs.node-version }}"
          echo "Entorno: ${{ inputs.entorno }}"
